name: betmaster
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    
    - assets/logos/BetMaster_Logo_Color.png
    
    - assets/fonts/argentum-sans.black-italic.ttf
    - assets/fonts/argentum-sans.black.ttf
    - assets/fonts/argentum-sans.bold-italic.ttf
    - assets/fonts/argentum-sans.bold.ttf
    - assets/fonts/argentum-sans.extrabold-italic.ttf
    - assets/fonts/argentum-sans.extrabold.ttf
    - assets/fonts/argentum-sans.extralight-italic.ttf
    - assets/fonts/argentum-sans.extralight.ttf
    - assets/fonts/argentum-sans.italic.ttf
    - assets/fonts/argentum-sans.light-italic.ttf
    - assets/fonts/argentum-sans.light.ttf
    - assets/fonts/argentum-sans.medium-italic.ttf
    - assets/fonts/argentum-sans.regular.ttf
    - assets/fonts/argentum-sans.semibold-italic.ttf
    - assets/fonts/argentum-sans.semibold.ttf
    - assets/fonts/argentum-sans.thin-italic.ttf
    - assets/fonts/argentum-sans.thin.ttf
  fonts:
    - family: Argentum Sans
      fonts:
        - asset: assets/fonts/argentum-sans.black-italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/argentum-sans.black.ttf
          weight: 900
        - asset: assets/fonts/argentum-sans.bold-italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/argentum-sans.bold.ttf
          weight: 700
        - asset: assets/fonts/argentum-sans.extrabold-italic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/argentum-sans.extrabold.ttf
          weight: 800
        - asset: assets/fonts/argentum-sans.extralight-italic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/argentum-sans.extralight.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/argentum-sans.italic.ttf
          style: italic
        - asset: assets/fonts/argentum-sans.light-italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/argentum-sans.light.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/argentum-sans.medium-italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/argentum-sans.regular.ttf
        - asset: assets/fonts/argentum-sans.semibold-italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/argentum-sans.semibold.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/argentum-sans.thin-italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/argentum-sans.thin.ttf
          weight: 100
          style: italic
